# Generated by Django 5.2.4 on 2025-07-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grn', '0002_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grn',
            name='parcel_type',
            field=models.CharField(choices=[('document', 'Document'), ('box', 'Box'), ('fragile', 'Fragile Item'), ('electronics', 'Electronics'), ('other', 'Other')], default='document', max_length=100),
        ),
    ]
