# Generated by Django 5.2.4 on 2025-07-31 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grn', '0003_alter_customuser_phone_alter_grn_parcel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grn',
            name='courier',
            field=models.CharField(blank=True, choices=[('DTDC', 'DTDC'), ('BlueDart', 'Blue Dart'), ('IndiaPost', 'India Post'), ('Delhivery', 'Delhivery'), ('EcomExpress', 'Ecom Express')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='grn',
            name='parcel_type',
            field=models.CharField(choices=[('document', 'Document'), ('box', 'Box'), ('fragile', 'Fragile Item'), ('electronics', 'Electronics'), ('other', 'Other')], default='', max_length=100),
        ),
    ]
