# Generated by Django 5.2.4 on 2025-08-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grn', '0004_alter_grn_courier_alter_grn_parcel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grn',
            name='courier',
            field=models.CharField(choices=[('professional_courier', 'Professional Courier'), ('blue_dart', 'Blue Dart'), ('branch_express', 'Branch Express'), ('dtdc', 'DTDC'), ('shree_maruthi', 'Shree Maruthi'), ('truck_on', 'Truck On'), ('express_air_service', 'Express Air Service'), ('st_retail', 'ST Retail'), ('post', 'Post'), ('sky_king', 'Sky King'), ('tirupathi', 'Tirupathi'), ('gokulam', 'Gokulam')], default='professional_courier', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grn',
            name='parcel_type',
            field=models.CharField(choices=[('document', 'Document'), ('cheque', 'Cheque'), ('bill', 'Bill'), ('sample', 'Sample'), ('box_cloths', 'Box (Cloths)'), ('food', 'Food'), ('medicine', 'Medicine')], max_length=100),
        ),
        migrations.AlterField(
            model_name='grn',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grn',
            name='sender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
