# Generated by Django 5.2.4 on 2025-08-20 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grn', '0005_alter_grn_courier_alter_grn_parcel_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dn',
            name='grn',
        ),
        migrations.RemoveField(
            model_name='grn',
            name='courier',
        ),
        migrations.RemoveField(
            model_name='grn',
            name='courier_id',
        ),
        migrations.RemoveField(
            model_name='grn',
            name='location',
        ),
        migrations.RemoveField(
            model_name='grn',
            name='parcel_type',
        ),
        migrations.RemoveField(
            model_name='grn',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='grn',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='grn',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='grn',
        ),
        migrations.AddField(
            model_name='grn',
            name='delivery_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grn_deliveries', to='grn.location'),
        ),
        migrations.CreateModel(
            name='GRNLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('sender_location', models.CharField(blank=True, max_length=255, null=True)),
                ('courier_name', models.CharField(choices=[('professional_courier', 'Professional Courier'), ('blue_dart', 'Blue Dart'), ('branch_express', 'Branch Express'), ('dtdc', 'DTDC'), ('shree_maruthi', 'Shree Maruthi'), ('truck_on', 'Truck On'), ('express_air_service', 'Express Air Service'), ('st_retail', 'ST Retail'), ('post', 'Post'), ('sky_king', 'Sky King'), ('tirupathi', 'Tirupathi'), ('gokulam', 'Gokulam')], max_length=50)),
                ('courier_id', models.CharField(blank=True, max_length=100, null=True)),
                ('parcel_type', models.CharField(choices=[('document', 'Document'), ('cheque', 'Cheque'), ('bill', 'Bill'), ('sample', 'Sample'), ('box_cloths', 'Box (Cloths)'), ('food', 'Food'), ('medicine', 'Medicine')], max_length=100)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('line_number', models.PositiveIntegerField(default=1)),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='grn.grn')),
            ],
            options={
                'ordering': ['line_number'],
                'unique_together': {('grn', 'line_number')},
            },
        ),
        migrations.AddField(
            model_name='dn',
            name='grn_line',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dn', to='grn.grnline'),
        ),
        migrations.AddField(
            model_name='otp',
            name='grn_line',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp', to='grn.grnline'),
        ),
    ]
