# Generated by Django 5.2.4 on 2025-08-26 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grn', '0006_remove_dn_grn_remove_grn_courier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='grn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_set', to='grn.grn'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='grn_line',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_otp', to='grn.grnline'),
        ),
        migrations.AlterUniqueTogether(
            name='otp',
            unique_together={('grn', 'valid')},
        ),
    ]
