# Generated by Django 5.2.4 on 2025-08-26 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grn', '0007_otp_grn_alter_otp_grn_line_alter_otp_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='otp',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='otp',
            name='grn_line',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp', to='grn.grnline'),
        ),
        migrations.RemoveField(
            model_name='otp',
            name='grn',
        ),
    ]
