# Generated by Django 5.2.4 on 2025-08-27 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grn', '0009_remove_dn_grn_line_remove_otp_grn_line_dn_grn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dn',
            name='grn',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='grn',
        ),
        migrations.AddField(
            model_name='dn',
            name='grn_line',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dn', to='grn.grnline'),
        ),
        migrations.AddField(
            model_name='otp',
            name='grn_line',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp', to='grn.grnline'),
        ),
    ]
