# Generated by Django 5.2.4 on 2025-08-27 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grn', '0010_remove_dn_grn_remove_otp_grn_dn_grn_line_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='grn_line',
        ),
        migrations.AddField(
            model_name='otp',
            name='grn',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp', to='grn.grn'),
        ),
    ]
