# Generated by Django 5.2.4 on 2025-09-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grn', '0011_remove_otp_grn_line_otp_grn'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_warehouse',
            field=models.BooleanField(default=False),
        ),
    ]
