# Generated by Django 5.2.4 on 2025-11-02 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grn', '0012_location_is_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseInward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inwarded_at', models.DateTimeField(auto_now_add=True)),
                ('floor', models.CharField(blank=True, max_length=100, null=True)),
                ('rack', models.CharField(blank=True, max_length=100, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('grn_line', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_inward', to='grn.grnline')),
                ('inwarded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_inwards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-inwarded_at'],
            },
        ),
    ]
