# Generated by Django 5.2.4 on 2025-11-03 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grn', '0013_warehouseinward'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouseinward',
            old_name='remark',
            new_name='delivery_remark',
        ),
        migrations.AddField(
            model_name='dn',
            name='from_warehouse_inward',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='warehouseinward',
            name='assigned_to_floor_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehouseinward',
            name='assigned_to_floor_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floor_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='warehouseinward',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehouseinward',
            name='delivered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='warehouseinward',
            name='delivered_to_receiver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='warehouseinward',
            name='floor_remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='warehouseinward',
            name='inward_remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
