# Generated by Django 5.2.4 on 2025-11-04 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grn', '0014_rename_remark_warehouseinward_delivery_remark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_warehouse_user',
            field=models.BooleanField(default=False, help_text='Designates whether this user is a warehouse user who creates GRNs.'),
        ),
        migrations.AddField(
            model_name='grn',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this GRN (warehouse user)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_grns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grn',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_grns', to=settings.AUTH_USER_MODEL),
        ),
    ]
