# Generated by Django 5.2.4 on 2025-12-12 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grn', '0016_alter_customuser_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='grn',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the GRN was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='grn',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this GRN', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_grns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grn',
            name='valid',
            field=models.BooleanField(default=True, help_text="If False, this GRN is considered deleted and won't show in frontend"),
        ),
        migrations.AddField(
            model_name='grnline',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the line was marked as deleted', null=True),
        ),
        migrations.AddField(
            model_name='grnline',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this line', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_grn_lines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grnline',
            name='valid',
            field=models.BooleanField(default=True, help_text="If False, this line is considered deleted and won't show in frontend"),
        ),
    ]
